### ISSUE TITLE
BasebandReader

### ISSUE THREAD

**Issue by 00rebe** [theXYZT/pulsarbat#42]
BasebandReader class does not need an intensity parameter and should be able to infer whether data is intensity data from the signal_type parameter.

**Comment by theXYZT** [comment]
It's not possible to tell if `intensity` should be True/False if `signal_type` is not a subclass of `pb.IntensitySignal` or `pb.BasebandSignal`. For example, when simply using `signal_type = pb.Signal`.

However, this should be a check that I am not doing right now. `signal_type` should be consistent with the `intensity` argument and should raise and Exception if they don't match.
